lease: /var/lib/dhcp/dhcpd.leases
database:
  type: sqlite3
  file: /var/lib/autoinstall/database.lib
binding:
  http:
    port: 8080
    address: 0.0.0.0
    root: /home/targuan/app/static
  tftp:
    port: 4242
    address: 0.0.0.0
    root: /dev/null

